name: bicos
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  mask_text_input_formatter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"


flutter:

  uses-material-design: true

  assets:

    - assets/user.png
    - assets/bicos_logo_sombra.png
    - assets/bicos_logo.png
    - assets/reset-password-icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/bicos_logo.psd"